name: Conda install

on:
  # Uncomment the below 'push' to trigger on push
  push:
    branches:
      - "**"
  schedule:
    # '*' is a special character in YAML, so string must be quoted
    - cron: "0 2 * * WED"
  workflow_dispatch: ~

jobs:
  conda-install:
    name: Conda install and test
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]
        version: [8, 9, 10, 11]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: Update conda
        run: |
          conda update conda

      - name: Install DOLFINx (py3-9)
        run: conda create -n env3-9 -c conda-forge python=3.9 fenics-dolfinx mpich
      - name: Test (py3-9)
        run: |
          conda run -n env3-9 python -c "import dolfinx; from mpi4py import MPI; dolfinx.mesh.create_rectangle(comm=MPI.COMM_WORLD, points=((0, 0), (2, 1)), n=(32, 16))"
          conda run -n env3-9 mpirun -np 2 python -c "import dolfinx; from mpi4py import MPI; dolfinx.mesh.create_rectangle(comm=MPI.COMM_WORLD, points=((0, 0), (2, 1)), n=(32, 16))"
